// netlify/functions/send-email.js

const RESEND_API_KEY = process.env.RESEND_API_KEY;

const headers = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers": "Content-Type, Authorization",
  "Access-Control-Allow-Methods": "POST, OPTIONS",
  "Content-Type": "application/json"
};

/**
 * HTML escape
 */
function escapeHtml(value) {
  return String(value ?? "")
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&#039;");
}

/**
 * Convert objects to readable HTML.
 */
function formatValue(value) {
  if (value === null || value === undefined) {
    return "";
  }

  if (typeof value === "object") {
    return escapeHtml(JSON.stringify(value, null, 2));
  }

  return escapeHtml(String(value));
}

/**
 * Build one HTML table.
 */
function renderSegment(segment) {

  const fields = Array.isArray(segment.fields)
    ? segment.fields
    : [];

  const isTable =
    fields.length > 1 &&
    fields.every(field =>
      field &&
      field.value &&
      typeof field.value === "object" &&
      !Array.isArray(field.value)
    );

  let html = `
<div style="margin-top:32px;">

<h2
style="
margin:0 0 14px;
font-size:18px;
color:#1e40af;
"
>
${escapeHtml(segment.segment_name || "Segment")}
</h2>
`;

  //
  // TABLE SEGMENT
  //

  if (isTable) {

    const columns = Object.keys(fields[0].value);

    html += `

<table
width="100%"
cellpadding="8"
cellspacing="0"
style="
border-collapse:collapse;
font-size:14px;
border:1px solid #d1d5db;
">

<thead>

<tr style="background:#eff6ff;">
`;

    for (const col of columns) {

      html += `
<th
align="left"
style="
border:1px solid #d1d5db;
">
${escapeHtml(col)}
</th>`;
    }

    html += `
</tr>

</thead>

<tbody>
`;

    for (const row of fields) {

      html += "<tr>";

      for (const col of columns) {

        html += `
<td
style="
border:1px solid #e5e7eb;
">
${formatValue(row.value[col])}
</td>
`;
      }

      html += "</tr>";
    }

    html += `
</tbody>

</table>
`;

  }

  //
  // NORMAL KEY/VALUE SEGMENT
  //

  else {

    html += `

<table
width="100%"
cellpadding="8"
cellspacing="0"
style="
border-collapse:collapse;
font-size:14px;
border:1px solid #d1d5db;
">
`;

    for (const field of fields) {

      html += `

<tr>

<td
style="
font-weight:bold;
width:220px;
background:#f9fafb;
border:1px solid #e5e7eb;
">
${escapeHtml(field.label)}
</td>

<td
style="
border:1px solid #e5e7eb;
white-space:pre-wrap;
">
${formatValue(field.value)}
</td>

</tr>
`;
    }

    html += `
</table>
`;
  }

  html += `
</div>
`;

  return html;

}


/**
 * Build the full email.
 */
function buildHtml(payload) {

  let html = `

<!DOCTYPE html>

<html>

<head>

<meta charset="utf-8">

</head>

<body
style="
font-family:Arial,Helvetica,sans-serif;
background:#f3f4f6;
padding:30px;
"
>

<div
style="
max-width:900px;
margin:auto;
background:white;
border-radius:10px;
padding:35px;
border:1px solid #e5e7eb;
"
>

<h1
style="
margin-top:0;
color:#1e40af;
"
>
Precifio Extract
</h1>

<p>

Your document has been successfully extracted.

</p>

<table
cellpadding="8"
cellspacing="0"
style="
border-collapse:collapse;
margin-top:20px;
margin-bottom:30px;
"
>

<tr>

<td><strong>Document</strong></td>

<td>${escapeHtml(payload.fileName)}</td>

</tr>

<tr>

<td><strong>Extracted</strong></td>

<td>${new Date().toLocaleString()}</td>

</tr>

`;

  if (payload.documentSummary) {

    html += `

<tr>

<td><strong>Summary</strong></td>

<td>${escapeHtml(payload.documentSummary)}</td>

</tr>

`;
  }

  html += `

</table>

`;

  const segments = Array.isArray(payload.segments)
    ? payload.segments
    : [];

  for (const segment of segments) {
    html += renderSegment(segment);
  }

    html += `

<div
style="
margin-top:40px;
padding-top:20px;
border-top:1px solid #e5e7eb;
font-size:12px;
color:#6b7280;
text-align:center;
"
>

Generated by <strong>Precifio Extract</strong>

</div>

</div>

</body>

</html>

`;

  return html;
}

exports.handler = async (event, context) => {

  context.callbackWaitsForEmptyEventLoop = false;

  if (event.httpMethod === "OPTIONS") {
    return {
      statusCode: 204,
      headers,
      body: ""
    };
  }

  if (event.httpMethod !== "POST") {
    return {
      statusCode: 405,
      headers,
      body: JSON.stringify({
        error: "Method not allowed"
      })
    };
  }

  if (!RESEND_API_KEY) {
    return {
      statusCode: 500,
      headers,
      body: JSON.stringify({
        error: "RESEND_API_KEY is missing."
      })
    };
  }

  try {

    const body = JSON.parse(event.body || "{}");

    const {
      to,
      subject,
      payload
    } = body;

    if (!to) {
      return {
        statusCode: 400,
        headers,
        body: JSON.stringify({
          error: "Recipient email is required."
        })
      };
    }

    if (!subject) {
      return {
        statusCode: 400,
        headers,
        body: JSON.stringify({
          error: "Subject is required."
        })
      };
    }

    if (!payload) {
      return {
        statusCode: 400,
        headers,
        body: JSON.stringify({
          error: "Payload is required."
        })
      };
    }

    const emailRegex =
      /^[^\s@]+@[^\s@]+\.[^\s@]+$/;

    if (!emailRegex.test(to)) {
      return {
        statusCode: 400,
        headers,
        body: JSON.stringify({
          error: "Invalid recipient email."
        })
      };
    }

    const html = buildHtml(payload);

    const resendResponse = await fetch(
      "https://api.resend.com/emails",
      {
        method: "POST",

        headers: {
          Authorization: `Bearer ${RESEND_API_KEY}`,
          "Content-Type": "application/json"
        },

        body: JSON.stringify({

          from: "Precifio Extract <noreply@precifio.app>",

          to,

          subject,

          html,

          text:
`Document: ${payload.fileName}

Summary:
${payload.documentSummary || "N/A"}

Generated by Precifio Extract`
        })
      }
    );

        const resendResult = await resendResponse.json();

    if (!resendResponse.ok) {
      console.error("Resend API Error:", resendResult);

      return {
        statusCode: resendResponse.status,
        headers,
        body: JSON.stringify({
          error:
            resendResult.message ||
            resendResult.error ||
            "Failed to send email.",
          details: resendResult
        })
      };
    }

    return {
      statusCode: 200,
      headers,
      body: JSON.stringify({
        success: true,
        message: "Email sent successfully.",
        resend: resendResult
      })
    };

  } catch (err) {

    console.error("send-email error:", err);

    return {
      statusCode: 500,
      headers,
      body: JSON.stringify({
        error: err.message || "Internal server error."
      })
    };

  }

};