[build]
  command = "npm run build"
  publish = "client/dist"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

[functions.extract]
  included_files = ["server/src/**"]

[functions.export]
  included_files = ["server/src/**"]

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200