import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import { generateFileName } from '../utils/fileName';

/**
 * ============================================================
 * Precifio Extract
 * AI Extraction Report
 * ============================================================
 */

function value(v) {
  if (v === null || v === undefined || v === '') return '—';
  return String(v);
}

function currency(extraction, amount) {
  if (amount === null || amount === undefined) return '—';

  if (typeof amount !== 'number')
    return value(amount);

  return `${extraction.currency || ''} ${amount.toLocaleString()}`.trim();
}

export function downloadAsPDF(extraction) {
  if (!extraction) {
    throw new Error('Nothing to export.');
  }

  const pdf = new jsPDF();

  let y = 20;

  // =====================================================
  // HEADER
  // =====================================================

  pdf.setFontSize(22);
  pdf.setTextColor(33, 150, 243);
  pdf.text('PRECIFIO EXTRACT', 15, y);

  y += 8;

  pdf.setFontSize(12);
  pdf.setTextColor(100);

  pdf.text('AI Document Extraction Report', 15, y);

  y += 12;

  pdf.setDrawColor(220);
  pdf.line(15, y, 195, y);

  y += 10;

  // =====================================================
  // DOCUMENT INFO
  // =====================================================

  pdf.setFontSize(15);
  pdf.setTextColor(0);
  pdf.text('Document Information', 15, y);

  y += 8;

  const infoRows = [
    ['Document Type', value(extraction.document_type)],
    ['Category', value(extraction.category)],
    ['Issue Date', value(extraction.issue_date)],
    ['Currency', value(extraction.currency)],
    ['Country', value(extraction.country)]
  ];

  autoTable(pdf, {
    startY: y,
    head: [['Field', 'Value']],
    body: infoRows,
    theme: 'grid',
    styles: {
      fontSize: 10
    }
  });

  y = pdf.lastAutoTable.finalY + 10;

  // =====================================================
  // PARTIES
  // =====================================================

  if (extraction.issuer || extraction.recipient) {

    pdf.setFontSize(15);
    pdf.text('Parties', 15, y);

    y += 6;

    autoTable(pdf, {
      startY: y,
      head: [['Role', 'Name']],
      body: [
        [
          'Issuer',
          value(
            extraction.issuer?.name ||
            extraction.vendor_name
          )
        ],
        [
          'Recipient',
          value(
            extraction.recipient?.name ||
            extraction.buyer_name
          )
        ]
      ]
    });

    y = pdf.lastAutoTable.finalY + 10;
  }

  // =====================================================
  // FINANCIAL SUMMARY
  // =====================================================

  const finance = [
    ['Subtotal', currency(extraction, extraction.subtotal)],
    ['Tax', currency(extraction, extraction.tax_amount)],
    ['Total', currency(extraction, extraction.total_amount)],
    ['Amount Due', currency(extraction, extraction.amount_due)]
  ];

  if (
    finance.some(r => r[1] !== '—')
  ) {

    pdf.setFontSize(15);
    pdf.text('Financial Summary', 15, y);

    y += 6;

    autoTable(pdf, {
      startY: y,
      head: [['Field', 'Value']],
      body: finance
    });

    y = pdf.lastAutoTable.finalY + 10;
  }

  // =====================================================
  // ITEMS
  // =====================================================

  const items =
    extraction.line_items ||
    extraction.items ||
    extraction.transactions;

  if (Array.isArray(items) && items.length) {

    pdf.setFontSize(15);
    pdf.text('Extracted Records', 15, y);

    y += 6;

    const columns = Object.keys(items[0]);

    autoTable(pdf, {
      startY: y,
      head: [columns],
      body: items.map(row =>
        columns.map(c => value(row[c]))
      ),
      styles: {
        fontSize: 8
      }
    });

    y = pdf.lastAutoTable.finalY + 10;
  }

  // =====================================================
  // OTHER FIELDS
  // =====================================================

  const ignored = [
    'issuer',
    'recipient',
    'line_items',
    'items',
    'transactions'
  ];

  const others = [];

  Object.entries(extraction).forEach(([key, val]) => {

    if (ignored.includes(key))
      return;

    if (
      typeof val === 'object' ||
      Array.isArray(val)
    )
      return;

    others.push([
      key.replace(/_/g, ' '),
      value(val)
    ]);

  });

  if (others.length) {

    pdf.setFontSize(15);
    pdf.text('Additional Fields', 15, y);

    y += 6;

    autoTable(pdf, {
      startY: y,
      head: [['Field', 'Value']],
      body: others
    });

    y = pdf.lastAutoTable.finalY + 10;
  }

  // =====================================================
  // FOOTER
  // =====================================================

  pdf.setFontSize(9);
  pdf.setTextColor(120);

  pdf.text(
    `Generated by Precifio AI • ${new Date().toLocaleString()}`,
    15,
    285
  );

  pdf.save(
    generateFileName(extraction, 'pdf')
  );
}